Itemset Class Reference
Represents a set of items with additional functionality for sequence analysis.
#include <itemset.hpp>
Public Member Functions
Itemset ()
Default constructor for an empty Itemset.
Itemset (const std::vector< int > &elements, const std::map< int, std::pair< int, int > > &initOccurrences={})
Constructs an Itemset from a vector of integers.
std::size_t hash () const
Computes the hash value for the Itemset.
void computeOccurrences (const std::vector< std::vector< int > > &sdb)
Computes occurrences of the itemset in a sequence database.
std::map< int, std::pair< int, int > > updateOccurrences (int item, const std::vector< std::vector< int > > &sdb)
Updates the occurrences by adding a new item.
void printOccurrences () const
Prints the occurrences for debugging purposes.
std::string toString () const
Converts the Itemset to a string representation.
std::map< int, std::pair< int, int > > getOccurrences () const
Retrieves the occurrences map.
bool isSubsetOf (const std::vector< int > &sequence) const
Checks if the Itemset is a subset of a given sequence.
std::vector< int > toSortedVector () const
Converts the Itemset to a sorted vector.
Private Attributes
std::map< int, std::pair< int, int > > occurrences
Map storing item occurrences within sequences.
Detailed Description
Represents a set of items with additional functionality for sequence analysis.
The Itemset class is an extension of std::set<int> with additional methods for managing occurrences, generating string representations, and computing relationships with sequences.
Definition at line 31 of file itemset.hpp.
Constructor & Destructor Documentation
Itemset() [1/2]
Itemset::Itemset () [inline]
Default constructor for an empty Itemset.
Initializes an empty set and an empty map of occurrences.
Definition at line 45 of file itemset.hpp.
: std::set<int>(), occurrences() {}
Itemset() [2/2]
Itemset::Itemset (const std::vector< int > & elements, const std::map< int, std::pair< int, int > > & initOccurrences = {}) [inline]
Constructs an Itemset from a vector of integers.
Parameters
elements A vector of integers to initialize the itemset.
initOccurrences Optional map of initial occurrences.
Definition at line 52 of file itemset.hpp.
                                                                                                    {})
    : std::set<int>(elements.begin(), elements.end()), occurrences(initOccurrences) {}
Member Function Documentation
computeOccurrences()
void Itemset::computeOccurrences (const std::vector< std::vector< int > > & sdb)
Computes occurrences of the itemset in a sequence database.
Parameters
sdb A sequence database represented as a vector of integer vectors.
Exceptions
std::logic_error if the Itemset is empty.
getOccurrences()
std::map< int, std::pair< int, int > > Itemset::getOccurrences () const
Retrieves the occurrences map.
Returns
A copy of the map storing the occurrences.
hash()
std::size_t Itemset::hash () const
Computes the hash value for the Itemset.
Returns
The computed hash value.
Combines the hash values of all elements in the itemset.
Referenced by std::hash< Itemset >::operator()().
isSubsetOf()
bool Itemset::isSubsetOf (const std::vector< int > & sequence) const
Checks if the Itemset is a subset of a given sequence.
Parameters
sequence A sequence of integers.
Returns
true if the Itemset is a subset of the sequence; otherwise, false.
Referenced by ERMiner::cooccurs().
printOccurrences()
void Itemset::printOccurrences () const
Prints the occurrences for debugging purposes.
Outputs the sequence ID and the range of occurrences for each sequence.
toSortedVector()
std::vector< int > Itemset::toSortedVector () const
Converts the Itemset to a sorted vector.
Returns
A vector containing the sorted elements of the Itemset.
toString()
std::string Itemset::toString () const
Converts the Itemset to a string representation.
Returns
A string representation of the Itemset.
updateOccurrences()
std::map< int, std::pair< int, int > > Itemset::updateOccurrences (int item, const std::vector< std::vector< int > > & sdb)
Updates the occurrences by adding a new item.
Parameters
item The item to add.
sdb The sequence database.
Returns
A map of updated occurrences.
Member Data Documentation
occurrences
std::map<int, std::pair<int, int> > Itemset::occurrences [private]
Map storing item occurrences within sequences.
The key represents the sequence ID, while the value is a pair of integers representing the first and last positions of the itemset in the sequence.
Definition at line 38 of file itemset.hpp.
The documentation for this class was generated from the following file:
include/itemset.hpp